/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId_'
import { Route as ProjectsProjectIdViewerRouteImport } from './routes/projects/$projectId_.viewer'
import { Route as ProjectsProjectIdIfcViewerRouteImport } from './routes/projects/$projectId_.ifc-viewer'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId_',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdViewerRoute = ProjectsProjectIdViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdIfcViewerRoute =
  ProjectsProjectIdIfcViewerRouteImport.update({
    id: '/ifc-viewer',
    path: '/ifc-viewer',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/tools': typeof ToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/ifc-viewer': typeof ProjectsProjectIdIfcViewerRoute
  '/projects/$projectId/viewer': typeof ProjectsProjectIdViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/tools': typeof ToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/ifc-viewer': typeof ProjectsProjectIdIfcViewerRoute
  '/projects/$projectId/viewer': typeof ProjectsProjectIdViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/tools': typeof ToolsRoute
  '/projects/$projectId_': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId_/ifc-viewer': typeof ProjectsProjectIdIfcViewerRoute
  '/projects/$projectId_/viewer': typeof ProjectsProjectIdViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/tools'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/ifc-viewer'
    | '/projects/$projectId/viewer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/tools'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/ifc-viewer'
    | '/projects/$projectId/viewer'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/tools'
    | '/projects/$projectId_'
    | '/projects/'
    | '/projects/$projectId_/ifc-viewer'
    | '/projects/$projectId_/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ToolsRoute: typeof ToolsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_': {
      id: '/projects/$projectId_'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/viewer': {
      id: '/projects/$projectId_/viewer'
      path: '/viewer'
      fullPath: '/projects/$projectId/viewer'
      preLoaderRoute: typeof ProjectsProjectIdViewerRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId_/ifc-viewer': {
      id: '/projects/$projectId_/ifc-viewer'
      path: '/ifc-viewer'
      fullPath: '/projects/$projectId/ifc-viewer'
      preLoaderRoute: typeof ProjectsProjectIdIfcViewerRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdIfcViewerRoute: typeof ProjectsProjectIdIfcViewerRoute
  ProjectsProjectIdViewerRoute: typeof ProjectsProjectIdViewerRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdIfcViewerRoute: ProjectsProjectIdIfcViewerRoute,
  ProjectsProjectIdViewerRoute: ProjectsProjectIdViewerRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ToolsRoute: ToolsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
